language: r
sudo: false
cache: packages
warnings_are_errors: true

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov(exclusions="R/Deprecated.R")'

r:
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change
